#docker-build-win64:
#  image: docker:latest
#  stage: build
#  services:
#    - docker:dind
#  before_script:    
#    - docker run --rm dockcross/windows-static-x86 > ./dockcross
#    - chmod +x ./dockcross
#    - cat ./dockcross
#  script:
#    - ./dockcross cmake -Bbuild -H. -GNinja
#    - ./dockcross ninja -Cbuild
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
docker-build-linux-x64:
  image: dockcross/linux-x64 
  stage: build
  script:
    #- git clone https://github.com/CapRat/plugin-torture.git && mkdir plugin-torture/build && cd plugin-torture/build && cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target install && cd ../..
    - cmake -P install.cmake
    - mkdir build
    - cd build
    - cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .  
  artifacts:
    paths:
      - build/
    expire_in: 30 mins
    
docker-test-linux-x64 :
  image: dockcross/linux-x64    
  stage: test
  script:
    - cd build
    - ctest  
  dependencies: 
    - docker-build-linux-x64

docker-deploy-linux-x64 :
  image: dockcross/linux-x64
  stage: deploy
  script:
    - cd build
    - echo Y | apt install rpm
    - cpack -G DEB .
    - cpack -G RPM .
    - cpack -G ZIP .
  dependencies:
    - docker-build-linux-x64
  artifacts:
    paths:
      - build
    expire_in: 30 mins
    
docker-build-win64:
  image: dockcross/windows-static-x64
  stage: build
  script:
    # - git clone https://github.com/CapRat/plugin-torture.git && mkdir plugin-torture/build && cd plugin-torture/build && cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target install && cd ../..
    - cmake -P install.cmake  
    - mkdir build
    - cd build
    - cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .


#docker-deploy-win64 :
#  image: dockcross/windows-static-x64
#  stage: deploy
#  script:
#    - cd build
#    - echo Y | apt install nsis
#    - cpack -G ZIP .
#    - cpack -G NSIS .
#  dependencies:
#    - docker-build-win64
#  artifacts:
#    paths:
#      - build
#    expire_in: 30 mins