#docker-build-win64:
#  image: docker:latest
#  stage: build
#  services:
#    - docker:dind
#  before_script:    
#    - docker run --rm dockcross/windows-static-x86 > ./dockcross
#    - chmod +x ./dockcross
#    - cat ./dockcross
#  script:
#    - ./dockcross cmake -Bbuild -H. -GNinja
#    - ./dockcross ninja -Cbuild
variables:
  GIT_SUBMODULE_STRATEGY: recursive
  
docker-build-linux-x64:
  image: debian:buster-slim 
  stage: build
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt --yes install cmake git ninja-build build-essential libstdc++6 pkg-config libxcb-util0-dev libx11-xcb-dev libxcb-util0-dev libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev
   # - DEBIAN_FRONTEND=noninteractive apt --yes --force-yes install libx11-dev libfreetype6-dev 	pkg-config libxcb-util0-dev libstdc++6 libx11-xcb-dev libxcb-util0-dev libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev
  script:
    #- git clone https://github.com/CapRat/plugin-torture.git && mkdir plugin-torture/build && cd plugin-torture/build && cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target install && cd ../..
    - mkdir -p build/Release
    - mkdir -p build/Debug     
    - mkdir deps
    - cmake -DINSTALL_PREFIX=deps/ -DBUILD_PATH=build/ -P scripts/install.cmake 
    - cd build/Release
    - cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release  -DCMAKE_PREFIX_PATH=build/ ../..
    - cmake --build .  
    - cd ../Debug
    - cmake -E env CXXFLAGS="-g -O0 -Wall -W -Wshadow -Wunused-variable -Wunused-parameter -Wunused-function -Wunused -Wno-system-headers -Wno-deprecated -Woverloaded-virtual -Wwrite-strings -fprofile-arcs -ftest-coverage" C_FLAGS="-g -O0 -Wall -W -fprofile-arcs -ftest-coverage" LDFLAGS="-fprofile-arcs -ftest-coverage -lgcov" cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release  -DCMAKE_PREFIX_PATH=build/ ../..
    - cmake --build .
  artifacts:    
    paths:
      - build/
    expire_in: 30 mins

docker_ubuntu_test:
  image: debian:buster-slim 
  stage: test
  before_script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive apt --yes install cmake git ninja-build build-essential libstdc++6 pkg-config libxcb-util0-dev libx11-xcb-dev libxcb-util0-dev libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev
   # - DEBIAN_FRONTEND=noninteractive apt --yes --force-yes install libx11-dev libfreetype6-dev 	pkg-config libxcb-util0-dev libstdc++6 libx11-xcb-dev libxcb-util0-dev libxcb-cursor-dev libxcb-xkb-dev libxkbcommon-dev libxkbcommon-x11-dev libfontconfig1-dev libcairo2-dev libgtkmm-3.0-dev libsqlite3-dev libxcb-keysyms1-dev
  script:
    #- git clone https://github.com/CapRat/plugin-torture.git && mkdir plugin-torture/build && cd plugin-torture/build && cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target install && cd ../..
    - cd build/Debug
    - ctest .
    - gcovr --fail-under-line 80 -s  --exclude-directories "test|examples"  -r ../..  .
    
#docker-test-linux-x64 :
#  image: dockcross/linux-x64    
#  stage: test
#  before_script:
#    #freeglut3-dev g++ libasound2-dev libcurl4-openssl-dev libfreetype6-dev libjack-jackd2-dev libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev mesa-common-dev ladspa-sdk webkit2gtk-4.0 libgtk-3-dev xvfb
#    - DEBIAN_FRONTEND=noninteractive apt --yes --force-yes install libasound2 libfreetype6 libx11-6 libxcomposite1 libxcursor1 libxinerama1 libxrandr2 libgtk-3-0 freeglut3 libjack-jackd2-0 xserver-xorg-video-dummy curl
#    - curl -o ./xorg.conf https://xpra.org/xorg.conf
#    - Xorg -noreset +extension GLX +extension RANDR +extension RENDER -logfile ./10.log -config ./xorg.conf :99 &
#    - export DISPLAY=:99
#    - sleep 3 # give xvfb some time to start
#  script:
#    - cd build
#    - ctest --verbose
#  dependencies: 
#    - docker-build-linux-x64

docker-deploy-linux-x64 :
  image: debian:buster-slim
  stage: deploy
  script:
    - cd build/Release
    - echo Y | apt install rpm
    - cpack -G DEB .
    - cpack -G RPM .
    - cpack -G ZIP .
  dependencies:
    - docker-build-linux-x64
  artifacts:
    paths:
      - build
    expire_in: 30 mins
    
#docker-build-win64:
#  image: dockcross/windows-static-x64
#  stage: build
#  script:
#    # - git clone https://github.com/CapRat/plugin-torture.git && mkdir plugin-torture/build && cd plugin-torture/build && cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --target install && cd ../..
#    - cmake -P scripts/install.cmake  
#    - mkdir build
#    - cd build
#    - cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release ..
#    - cmake --build .


#docker-deploy-win64 :
#  image: dockcross/windows-static-x64
#  stage: deploy
#  script:
#    - cd build
#    - echo Y | apt install nsis
#    - cpack -G ZIP .
#    - cpack -G NSIS .
#  dependencies:
#    - docker-build-win64
#  artifacts:
#    paths:
#      - build
#    expire_in: 30 mins
