

function(EXPORT_SYMBOLS EXPORT_SYMBOLS_TARGET)
if(WIN32)
        set(oneValueArgs OUTDIR FILE_NAME)
        set(multiValueArgs FUNCTION_NAMES)
        cmake_parse_arguments(EXPORT_SYMBOLS "" "${oneValueArgs}" "${multiValueArgs}" ${ARGN} )
       
       if(NOT EXPORT_SYMBOLS_OUTDIR)
            set(EXPORT_SYMBOLS_OUTDIR ${PROJECT_BINARY_DIR}/generated/)
       endif(NOT EXPORT_SYMBOLS_OUTDIR)  
       if(NOT EXPORT_SYMBOLS_FILE_NAME )
            set(EXPORT_SYMBOLS_FILE_NAME ${EXPORT_SYMBOLS_TARGET}_export.def)
       endif(NOT EXPORT_SYMBOLS_FILE_NAME)

       string (REPLACE ";" "\n  " EXPORT_SYMBOLS_NEWLINED_FUNCTION_NAMES "${EXPORT_SYMBOLS_FUNCTION_NAMES}")
       file(WRITE ${EXPORT_SYMBOLS_OUTDIR}/${EXPORT_SYMBOLS_FILE_NAME} "EXPORTS \n  ${EXPORT_SYMBOLS_NEWLINED_FUNCTION_NAMES}")
        
       target_sources(${EXPORT_SYMBOLS_TARGET} INTERFACE  ${EXPORT_SYMBOLS_OUTDIR}/${EXPORT_SYMBOLS_FILE_NAME})
endif(WIN32)
     #target_include_directories(${GENERATE_VERSION_HEADER_TARGET} PUBLIC ${GENERATE_VERSION_HEADER_OUTDIR})
endfunction(GENERATE_VERSION_HEADER)

